### PR TITLE
Converted to Swift 3

### PR DESCRIPTION
**Pull request by throneware**

### CODE REVIEW

**Comment by JanHalozan** [comment]
Nice! Thank you. Before I merge can you please take care of the indentation issues? See the diff.

**Comment by throneware** [comment]
Ah sorry I hadn’t noticed that. I did a diff locally and they didn’t show up. 

Will sort it out!

Best Regards,
Throneware Ltd.
www.throneware.com <http://www.throneware.com/>

**Comment by throneware** [comment]
@JanHalozan There you go.

**Comment by JanHalozan** [comment]
Thank you!

**Pull request merged**
